# Generated by Django 4.1.2 on 2022-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('skills', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('github', models.URLField()),
                ('external', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
